options renaming, upgrader, and roxygen2
jasp-stats/jaspJags pull request #70
Opened 2022-07-28 09:55 UTC by vandenman

Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1986

2022-07-28 11:04 UTC, Kucharssim requested changes
Looks good, just one suggestion!

2022-07-28 11:04 UTC, Kucharssim commented on inst/qml/JAGS.qml
>  					name: "noLags"
```suggestion
					name: "autoCorPlotLags"
```

2022-08-05 13:21 UTC, Kucharssim approved these changes
Looks good! The options are upgraded correctly, but running a test using `--unitTest` errors out because of little differences in the output (presumably due to sampling variation) . It is odd because I tried to use the `setSeed` option which works fine within one specific version, but different versions of the modules lead to slightly different results... If that's known and not an issue (aka we cannot fix this behavior), we can merge this.

2022-08-08 12:19 UTC, vandenman commented
> It is odd because I tried to use the setSeed option which works fine within one specific version, but different versions of the modules lead to slightly different results... If that's known and not an issue (aka we cannot fix this behavior), we can merge this.

If you made the original file with the released 0.16.3 (or used one from the data library), then the shipped Jags version is probably different. Also, the seed is a bit of a lie since Jags isn't reproducible at all across OSes, so any data library file is probably not reproducible ever.

2022-08-08 12:21 UTC, merged